config/routes.rb
Frontenis::Application.routes.draw do

  get "statistics/index"
  get 'statistics/user/:id' => 'statistics#user'
  get "rankings/index"

  resources :championships
  resources :games
  resources :users

  root :to => 'games#index'

end

app/models/championship.rb
class Championship < ActiveRecord::Base

  has_many :games
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  # GET /championships
  # GET /championships.json
  def index
    @championships = Championship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @championships }
    end
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
    @championship = Championship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @championship }
    end
  end

  # GET /championships/new
  # GET /championships/new.json
  def new
    @championship = Championship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @championship }
    end
  end

  # GET /championships/1/edit
  def edit
    @championship = Championship.find(params[:id])
  end

  # POST /championships
  # POST /championships.json
  def create
    @championship = Championship.new(championship_params)

    respond_to do |format|
      if @championship.save
        format.html { redirect_to @championship, notice: 'Championship was successfully created.' }
        format.json { render json: @championship, status: :created, location: @championship }
      else
        format.html { render action: "new" }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /championships/1
  # PUT /championships/1.json
  def update
    @championship = Championship.find(params[:id])

    respond_to do |format|
      if @championship.update_attributes(championship_params)
        format.html { redirect_to @championship, notice: 'Championship was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship = Championship.find(params[:id])
    @championship.destroy

    respond_to do |format|
      format.html { redirect_to championships_url }
      format.json { head :ok }
    end
  end


  private

  def championship_params
    params.require(:championship).permit(:name, :start_date,:finish_date, :created_at, :updated_at)
  end

end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_form.html.erb
<%= form_for(@championship) do |f| %>
  <% if @championship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@championship.errors.count, "error") %> prohibited this championship from being saved:</h2>

      <ul>
      <% @championship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :finish_date %><br />
    <%= f.date_select :finish_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/championships/edit.html.erb
<h1>Editing championship</h1>

<%= render 'form' %>

<%= link_to 'Show', @championship %> |
<%= link_to 'Back', championships_path %>

app/views/championships/index.html.erb
<h1>Listing championships</h1>


<% @championships.each do |championship| %>
  <p>
    <span><%= championship.start_date %></span>
    <span><%= championship.finish_date %></span>
    <span><%= championship.name %></span>

    Not Asigned!!!!
      <ul>
        <% Game.where("played >= :start AND played <= :finish", {:start => championship.start_date, :finish => championship.finish_date }).each do |game| %>
          <% if championship.id != game.championship_id %>

          <%= form_for(game) do |f| %>


          <table>
            <tr>
              <td>
                <%= link_to game.id, game %>
              </td>
              <td>
                <%= game.played %>
              </td>
              <td>
                  <%= f.collection_select :championship_id, Championship.order(start_date: :desc), :id, :name, {} %>
              </td>
              <td>
                <%= f.submit %>
              </td>
            </tr>
          </table>
          <% end %>

          <% end %>
        <% end %>
      </ul>
</p>
<% end %>



<br />

<%= link_to 'New Championship', new_championship_path %>

app/views/championships/new.html.erb
<h1>New championship</h1>

<%= render 'form' %>

<%= link_to 'Back', championships_path %>

app/views/championships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @championship.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @championship.start_date %>
</p>

<p>
  <b>Finish date:</b>
  <%= @championship.finish_date %>
</p>


<%= link_to 'Edit', edit_championship_path(@championship) %> |
<%= link_to 'Back', championships_path %>