config/routes.rb
Frontenis::Application.routes.draw do

  get "statistics/index"
  get 'statistics/user/:id' => 'statistics#user'
  get "rankings/index"

  resources :championships
  resources :games
  resources :users

  root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :championship
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index

    @championships = Championship.order(start_date: :desc)

    if params[:championship_id]
      @games = Game.order(played: :desc).where("championship_id = ?", params[:championship_id])
    else
      @games = Game.order(played: :desc).all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(game_params)
        format.html { redirect_to games_path, notice: 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end

private
  def game_params
    params.require(:game).permit(:played,:t1_p1,:t1_p2,:t1_points,:t2_p1,:t2_p2,:t2_points,:created_at,:updated_at,:championship_id)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table>
  <tr>
    <td>
      <div class="field">
          <%= f.collection_select :championship_id, Championship.order(start_date: :desc), :id, :name, {} %>
      </div>
      <br>
      <div class="field">
        <%= f.label :played %><br />
        <%= f.datetime_select :played %>
      </div>
    </td>
    <td>
<table>
  <tr>
    <td>TEAM 1</td>
    <td>TEAM 2</td>
  </tr>
  <tr>
    <td>
      <div class="field">
        <%= f.number_field :t1_points %>
      </div>
      <div class="field">
        <%= f.collection_select :t1_p1, User.order(:name), :id, :name, { :prompt => 'Select player'} %>
      </div>
      <div class="field">
        <%= f.collection_select :t1_p2, User.order(:name), :id, :name, { :prompt => 'Select player'} %>
      </div>
    </td>
    <td>
      <div class="field">
        <%= f.number_field :t2_points %>
      </div>
      <div class="field">
        <%= f.collection_select :t2_p1, User.order(:name), :id, :name, { :prompt => 'Select player'} %>
      </div>
      <div class="field">
        <%= f.collection_select :t2_p2, User.order(:name), :id, :name, { :prompt => 'Select player'} %>
      </div>
    </td>
  </tr>
</table>
    </td>
  </tr>
</table>









  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="row">

  <div class="col-md-9">

    <table style="cellspacing:200px">
      <%
      last_game_date = ''
      @games.each do |game|

        if last_game_date != game.played.to_date
          last_game_date = game.played.to_date
          %>
        </tr>
        <tr>
          <td>
            <% played_time = game.played %>
            <time datetime="<%=played_time.to_date %>" class="icon">
              <em><%= played_time.strftime("%A") %></em>
              <strong><%= played_time.strftime("%B") %></strong>
              <span><%= played_time.day %></span>
            </time>
          </td>
          <% end %>
          <td>
            <table>
              <tr>
                <td colspan='2' style='text-align: center'>
                  <h2><%= game.t1_points %> - <%= game.t2_points %></h2>
                </td>
              </tr>
              <tr>
                <td><%= User.find(game.t1_p1).name %></td>
                <td><%= User.find(game.t2_p1).name %></td>
              </tr>
              <tr>
                <td><%= User.find(game.t1_p2).name %></td>
                <td><%= User.find(game.t2_p2).name %></td>
              </tr>
            </table>
          </td>
          <% end %>

        </table>

  </div>

  <div class="col-md-3">

    <div class="panel panel-default">
      <div class="panel-heading">
        Championships (<%= link_to 'All', controller: "games", action: "index"%>)
      </div>
      <div class="panel-body">
        <% @championships.each do |cs| %>
        <p>
          <%= link_to cs.name, controller: "games", action: "index", championship_id: cs.id %>
        </p>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @game.played %></h1>

<table>
    <tr>
      <td><%= User.find(@game.t1_p1).name %></td>
      <td rowspan='2'><h2><%= @game.t1_points %></h2></td>
      <td rowspan='2'><h2>-</h2></td>
      <td rowspan='2'><h2><%= @game.t2_points %></h2></td>
      <td><%= User.find(@game.t2_p1).name %></td>
  </tr>
  <tr>
      <td><%= User.find(@game.t1_p2).name %></td>
      <td><%= User.find(@game.t2_p2).name %></td>
  </tr>
</table>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>